_wandb:
    value:
        cli_version: 0.18.7
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 71
                - 98
                - 106
            "2":
                - 1
                - 11
                - 49
                - 55
                - 71
                - 98
                - 106
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.11.10
            "5": 0.18.7
            "6": 4.46.3
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 8
cache_dir:
    value: cache
dataset_path:
    value: data/bindingdb/cv0/train.csv
dropout:
    value: 0.1
drug_smiles_column:
    value: smiles
experiment_name:
    value: demo
learning_rate:
    value: 0.0001
lora_alpha:
    value: 32
lora_dropout:
    value: 0
lora_r:
    value: 4
measure_name:
    value: label
num_classes:
    value: 1
num_epochs:
    value: 10
num_gpus:
    value: 1
num_target_encoders_tuned:
    value: 1
num_workers:
    value: 4
protein_model_name:
    value: facebook/esm2_t36_3B_UR50D
protein_sequence_column:
    value: target_sequence
seed:
    value: 42
train_ratio:
    value: 0.8
val_ratio:
    value: 0.1
